# Generated by Django 6.1.1 on 2026-09-29 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderGate',
            fields=[
                ('provider', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('next_allowed', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('opis_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('source_prices', models.JSONField(default=list)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('coordinate_source', models.TextField(blank=True)),
                ('geocode_status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('geocode_result', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='planner_sta_latitud_cbe592_idx')],
            },
        ),
    ]
